version: '3.4'

services:
  powerplant-coding-challenge:
    image: powerplantcodingchallenge:dev
    container_name: powerplant-coding-challenge
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "powerplant-coding-challenge"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages
    volumes:
      - /Users/macbookair/Projects/repo/powerplant-coding-challenge/powerplant-coding-challenge:/app
      - /Users/macbookair/Projects/repo/powerplant-coding-challenge:/src
      - /Users/macbookair/vsdbg/vs2017u5:/remote_debugger:rw
      - /Users/macbookair/.nuget/packages/:/root/.nuget/packages:ro
      - /usr/local/share/dotnet/sdk/NuGetFallbackFolder:/root/.nuget/fallbackpackages:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  \"/app/bin/Debug/net6.0/powerplant-coding-challenge.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true